### ISSUE TITLE
Bug: "Failed to activate the fountain package"

### ISSUE THREAD

**Issue by X-Raym** [superlou/fountain-atom#59]
Hi,

I got a bug on activating the fountain-atom package.

Note that deactivated all the community module for testing, and also tested in a fresh atom install, so it is likely to be a problem in the module.

[Enter steps to reproduce:]

1. Fresh atom install
2. Install fountain-aom

**Atom**: 1.26.0 x64
**Electron**: 1.7.11
**OS**: Unknown Windows version
**Thrown From**: [fountain](https://github.com/superlou/fountain-atom) package 0.7.2

### Stack Trace

Failed to activate the fountain package

```
At Cannot read property 'isEqual' of undefined

TypeError: Cannot read property 'isEqual' of undefined
    at editorsWithMaintainedConfig.forEach (~/AppData/Local/atom/app-1.26.0/resources/app/src/text-editor-registry.js:261:56)
    at Set.forEach (native)
    at subscriptions.add.config.onDidChange (~/AppData/Local/atom/app-1.26.0/resources/app/src/text-editor-registry.js:260:52)
    at emitter.on (~/AppData/Local/atom/app-1.26.0/resources/app/src/config.js:1290:15)
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.26.0/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.26.0/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Config.emitChangeEvent (~/AppData/Local/atom/app-1.26.0/resources/app/src/config.js:1226:62)
    at Config.setRawScopedValue (~/AppData/Local/atom/app-1.26.0/resources/app/src/config.js:1255:23)
    at Config.set (~/AppData/Local/atom/app-1.26.0/resources/app/src/config.js:713:18)
    at ScopedProperties.module.exports.ScopedProperties.activate (~/AppData/Local/atom/app-1.26.0/resources/app/src/scoped-properties.js:31:27)
    at Package.activateResources (~/AppData/Local/atom/app-1.26.0/resources/app/src/package.js:326:24)
    at measure (~/AppData/Local/atom/app-1.26.0/resources/app/src/package.js:202:24)
    at Package.measure (~/AppData/Local/atom/app-1.26.0/resources/app/src/package.js:88:25)
    at activationPromise.Promise (~/AppData/Local/atom/app-1.26.0/resources/app/src/package.js:200:20)
    at Promise (<anonymous>)
    at Package.activate (~/AppData/Local/atom/app-1.26.0/resources/app/src/package.js:198:38)
    at PackageManager.activatePackage (~/AppData/Local/atom/app-1.26.0/resources/app/src/package-manager.js:695:42)
    at packagesToEnable.forEach.name (~/AppData/Local/atom/app-1.26.0/resources/app/src/package-manager.js:440:51)
    at Array.forEach (native)
    at disabledPackagesSubscription.config.onDidChange (~/AppData/Local/atom/app-1.26.0/resources/app/src/package-manager.js:440:30)
    at emitter.on (~/AppData/Local/atom/app-1.26.0/resources/app/src/config.js:1067:22)
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.26.0/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.26.0/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Config.emitChangeEvent (~/AppData/Local/atom/app-1.26.0/resources/app/src/config.js:1226:62)
    at Config.setRawValue (~/AppData/Local/atom/app-1.26.0/resources/app/src/config.js:1052:23)
    at Config.set (~/AppData/Local/atom/app-1.26.0/resources/app/src/config.js:715:18)
    at Config.removeAtKeyPath (~/AppData/Local/atom/app-1.26.0/resources/app/src/config.js:905:16)
    at Package.enable (~/AppData/Local/atom/app-1.26.0/resources/app/src/package.js:75:30)
    at PackageManager.enablePackage (~/AppData/Local/atom/app-1.26.0/resources/app/src/package-manager.js:246:18)
    at HTMLButtonElement.enablementButtonClickHandler (~/AppData/Local/atom/app-1.26.0/resources/app/node_modules/settings-view/lib/package-card.js:362:31)
```

### Commands

```
```

### Non-Core Packages

```
animated-page-scroll 1.2.0 
atom-beautify 0.32.2 
atom-html-preview 0.2.5 
atom-lupa 0.7.43 
autoupdate-packages 1.3.1 
browser-plus 0.0.98 
busy-signal 1.4.3 
click-link 1.0.11 
color-tabs 0.1.8 
compare-files 0.8.1 
docblockr 0.13.7 
file-icons 2.1.19 
fountain 0.7.2 
git-diff-details 1.4.0 
git-time-machine 1.5.9 
highlight-bad-chars 1.0.7 
highlight-nbsp 0.1.1 
intentions 1.1.5 
language-generic-config 1.4.0 
language-lua 0.9.11 
language-reaperlangpack 0.0.1 
language-srt 0.1.1 
linter 2.2.0 
linter-js-standard 5.0.0 
linter-ui-default 1.7.1 
markdown-scroll-sync 2.1.2 
minimap 4.29.8 
minimap-pigments 0.2.2 
open-in-browsers 0.0.30 
pane-browser 1.6.0 
pdf-view 0.69.0 
pigments 0.40.2 
quick-highlight 0.13.0 
script 3.18.0 
snippet-generator 0.3.2 
sort-lines 0.18.0 
source-preview 0.5.3 
space-tab 0.4.2 
split-diff 1.5.2 
standard-formatter 2.8.0 
symbols-tree-view 0.14.0 
tab-control 0.6.10 
tab-smart-sort 0.3.0 
teletype 0.13.1 
todo-show 2.3.0 
trailing-spaces 0.4.0 
tree-view-filter 0.5.3 
vtt-helper 0.1.1 
wordcount 2.10.4 
wordpress-api 1.2.2 
```

This 'isEqual' message error also happen when the package is installed and activated you try to set Settings->Editor->Past scroll ends.

It also causes interactions with other packages like todo-show which is unable to close right when fountain-atom is active.

Thanks for taking a look :)

**Comment by X-Raym** [comment]
Also, the Scroll Past End settings isnt saved at Atom close/restart, due to this isEqual bug.

**Comment by superlou** [comment]
The really interesting thing is that the stack trace doesn't mention any of the fountain files. Grasping at straws, I think it might be similar to https://github.com/atom/atom/issues/16394. Can you try starting in safe mode and seeing if you get the same error?

**Comment by X-Raym** [comment]
@superlou Damn I tested again I can't reproduce. I tested especially on a atom installed with only fountain-atom when I reported the error. to be sure.. Though, I still have the errors when I activate the Scroll past end function but even without fountain-atom installed.

I'm inspecting further and I'll let you now if I succeed to reproduce it again.

But if you can't reproduce maybe it is something related to another package somehow.

**Comment by X-Raym** [comment]
Retried on a fresh install, it seems the problem maybe more related to the todo-show package... I close this issue, and I'll re-open it if needed. Sorry for the inconvenience :S

**Comment by superlou** [comment]
No problem! Glad you got it worked out.

**Comment by Meridiansun** [comment]
I believe the offending package is todo-show 2.3.0.  I loaded it in for the first time last night and started seeing the errors when going to preferences and checking/unchecking soft wrap under the editor tab.  I turned off all non-standard packages except todo-show 2.3.0 and the error appears.  I turn todo-show 2.3.0 off and restart Atom and the error is gone.

**Comment by Nyhde** [comment]
Hi,

I hope it's okay to continue this discussion even though the thread has been buried for a couple of years.

The thing is, I tried setting up Atom and the fountain-atom package. I'm new to both, but basic troubleshooting I can handle.

The error message I got was this:

"Cannot find module 'underscore-plus'"

Obviously, I tried downloading the newest version of this said package. For whatever reason Atom doesn't seem to find it, no matter whether I rename it or not.

Could someone please help me? An editor capable of handling exporting and structuring Fountain would be a most welcome addition to my workflow.

**Comment by X-Raym** [comment]
@Nyhde I'm not sure the sourve of the issue is same as mine,
I suggest you to open a new issue directly it will be better to discuss this.
