### ISSUE TITLE
fountain package fails to install

### ISSUE THREAD

**Issue by bilbo50** [superlou/fountain-atom#68]
Greetings!
I cannot get the fountain package to install on Atom on Windows 10.  I had completely uninstalled Atom with IObit Uninstaller, and thus (presumably) removed any files from an old (non-git) version of Atom; then I installed the latest version of Atom.

However, I was able to install the symbols-view package---it installed immediately, without an error.

 I'm new to GitHub but I've installed the Windows GitHub desktop app and am able to log onto GitHub with my ID and PW. 

The gist of the problem, reported in the messsages, seems to be:
=====================================

npm ERR! Command failed: git -c core.longpaths=true clone --template=C:\Users\Dave the K\.atom\.apm\_git-remotes\_templates --mirror git@github.com:requirejs/text.git C:\Users\Dave the K\.atom\.apm\_git-remotes\git-github-com-requirejs-text-git-e7ab515b

npm ERR! Cloning into bare repository 'C:\Users\Dave the K\.atom\.apm\_git-remotes\git-github-com-requirejs-text-git-e7ab515b'...

npm ERR! Host key verification failed.

npm ERR! fatal: Could not read from remote repository.
 
npm ERR! Please make sure you have the correct access rights

npm ERR! and the repository exists.

=====================================

Thanks in advance for any help/insight into this problem!

[Atom Failed-Install Error Messages.txt](https://github.com/superlou/fountain-atom/files/2176460/Atom.Failed-Install.Error.Messages.txt)

**Comment by superlou** [comment]
@bilbo50, did you install the package using the [instructions here](https://flight-manual.atom.io/using-atom/sections/atom-packages/)? Did you use the GUI or the `apm` command line? You shouldn't need a GitHub account to install an Atom package for normal usage.

**Comment by bilbo50** [comment]
Yes, the GUI in Atom:  "File",  Settings tab opens, Install Packages, search for "fountain" package, click on "Install" button.  "C:" drive light grinds along for about 10 seconds, and then always get "Installing “fountain@0.7.3” failed. Show output…" message.

**Comment by superlou** [comment]
Can you try installing via the APM command-line tool? Run `apm install fountain` in a command prompt and paste the results.

**Comment by jrbostic** [comment]
I'm wondering if this might not be similar to the problem I had a while back with uninstalling atom.  There were some hidden config file(s) that didn't get cleaned up... I had to manually remove.  Unfortunately, I don't know where it drops this config file on Windows... Maybe track that down before you try to reinstall atom.

**Comment by bilbo50** [comment]
Hello, 

I opened a windows console "CMD.EXE" and ran "apm install fountain". 
Here are the results: 
===================================================== 
Microsoft Windows [Version 10.0.17134.165] 
(c) 2018 Microsoft Corporation. All rights reserved. 

C:\Users\Dave the K>apm install fountain 
Installing fountain to C:\Users\Dave the K\.atom\packages 1 [main] sh 20156 fork: child -1 - forked process 20172 died unexpectedly, retry 0, exit code 0xC0000142, errno 11 
1272306 [main] sh 20156 fork: child -1 - forked process 20212 died unexpectedly, retry 0, exit code 0xC0000142, errno 11 
3502204 [main] sh 20156 fork: child -1 - forked process 19508 died unexpectedly, retry 0, exit code 0xC0000142, errno 11 
7733870 [main] sh 20156 fork: child -1 - forked process 19792 died unexpectedly, retry 0, exit code 0xC0000142, errno 11 
15976265 [main] sh 20156 fork: child -1 - forked process 7672 died unexpectedly, retry 0, exit code 0xC0000142, errno 11 
1 [main] sh 15612 fork: child -1 - forked process 10468 died unexpectedly, retry 0, exit code 0xC0000142, errno 11 
1260089 [main] sh 15612 fork: child -1 - forked process 19708 died unexpectedly, retry 0, exit code 0xC0000142, errno 11 
3471657 [main] sh 15612 fork: child -1 - forked process 20200 died unexpectedly, retry 0, exit code 0xC0000142, errno 11 
7702774 [main] sh 15612 fork: child -1 - forked process 20400 died unexpectedly, retry 0, exit code 0xC0000142, errno 11 
15935337 [main] sh 15612 fork: child -1 - forked process 19732 died unexpectedly, retry 0, exit code 0xC0000142, errno 11 
failed 

npm ERR! git submodule -q update --init --recursive: 1 [main] sh 20156 fork: child -1 - forked process 20172 died unexpectedly, retry 0, exit code 0xC0000142, errno 11 
npm ERR! git submodule -q update --init --recursive: C:/Program Files/Git/mingw64/libexec/git-core\git-submodule: fork: retry: Resource temporarily unavailable 
npm ERR! git submodule -q update --init --recursive: 1272306 [main] sh 20156 fork: child -1 - forked process 20212 died unexpectedly, retry 0, exit code 0xC0000142, errno 11 
npm ERR! git submodule -q update --init --recursive: C:/Program Files/Git/mingw64/libexec/git-core\git-submodule: fork: retry: Resource temporarily unavailable 
npm ERR! git submodule -q update --init --recursive: 3502204 [main] sh 20156 fork: child -1 - forked process 19508 died unexpectedly, retry 0, exit code 0xC0000142, errno 11 
npm ERR! git submodule -q update --init --recursive: C:/Program Files/Git/mingw64/libexec/git-core\git-submodule: fork: retry: Resource temporarily unavailable 
npm ERR! git submodule -q update --init --recursive: 7733870 [main] sh 20156 fork: child -1 - forked process 19792 died unexpectedly, retry 0, exit code 0xC0000142, errno 11 
npm ERR! git submodule -q update --init --recursive: C:/Program Files/Git/mingw64/libexec/git-core\git-submodule: fork: retry: Resource temporarily unavailable 
npm ERR! git submodule -q update --init --recursive: 15976265 [main] sh 20156 fork: child -1 - forked process 7672 died unexpectedly, retry 0, exit code 0xC0000142, errno 11 
npm ERR! git submodule -q update --init --recursive: C:/Program Files/Git/mingw64/libexec/git-core\git-submodule: fork: Resource temporarily unavailable 
npm ERR! git submodule -q update --init --recursive: 
npm ERR! git submodule -q update --init --recursive: 1 [main] sh 15612 fork: child -1 - forked process 10468 died unexpectedly, retry 0, exit code 0xC0000142, errno 11 
npm ERR! git submodule -q update --init --recursive: C:/Program Files/Git/mingw64/libexec/git-core\git-submodule: fork: retry: Resource temporarily unavailable 
npm ERR! git submodule -q update --init --recursive: 1260089 [main] sh 15612 fork: child -1 - forked process 19708 died unexpectedly, retry 0, exit code 0xC0000142, errno 11 
npm ERR! git submodule -q update --init --recursive: C:/Program Files/Git/mingw64/libexec/git-core\git-submodule: fork: retry: Resource temporarily unavailable 
npm ERR! git submodule -q update --init --recursive: 3471657 [main] sh 15612 fork: child -1 - forked process 20200 died unexpectedly, retry 0, exit code 0xC0000142, errno 11 
npm ERR! git submodule -q update --init --recursive: C:/Program Files/Git/mingw64/libexec/git-core\git-submodule: fork: retry: Resource temporarily unavailable 
npm ERR! git submodule -q update --init --recursive: 7702774 [main] sh 15612 fork: child -1 - forked process 20400 died unexpectedly, retry 0, exit code 0xC0000142, errno 11 
npm ERR! git submodule -q update --init --recursive: C:/Program Files/Git/mingw64/libexec/git-core\git-submodule: fork: retry: Resource temporarily unavailable 
npm ERR! git submodule -q update --init --recursive: 15935337 [main] sh 15612 fork: child -1 - forked process 19732 died unexpectedly, retry 0, exit code 0xC0000142, errno 11 
npm ERR! git submodule -q update --init --recursive: C:/Program Files/Git/mingw64/libexec/git-core\git-submodule: fork: Resource temporarily unavailable 
npm ERR! git submodule -q update --init --recursive: 
npm WARN addRemoteGit Error: Command failed: git -c core.longpaths=true config --get remote.origin.url 
npm WARN addRemoteGit 
npm WARN addRemoteGit at ChildProcess.exithandler (child_process.js:206:12) 
npm WARN addRemoteGit at emitTwo (events.js:106:13) 
npm WARN addRemoteGit at ChildProcess.emit (events.js:191:7) 
npm WARN addRemoteGit at maybeClose (internal/child_process.js:877:16) 
npm WARN addRemoteGit at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5) 
npm WARN addRemoteGit requirejs/text resetting remote C:\Users\Dave the K\.atom\.apm\_git-remotes\git-github-com-requirejs-text-git-e7ab515b because of error: { Error: Command failed: git -c core.longpaths=true config --get remote.origin.url 
npm WARN addRemoteGit 
npm WARN addRemoteGit at ChildProcess.exithandler (child_process.js:206:12) 
npm WARN addRemoteGit at emitTwo (events.js:106:13) 
npm WARN addRemoteGit at ChildProcess.emit (events.js:191:7) 
npm WARN addRemoteGit at maybeClose (internal/child_process.js:877:16) 
npm WARN addRemoteGit at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5) 
npm WARN addRemoteGit killed: false, 
npm WARN addRemoteGit code: 1, 
npm WARN addRemoteGit signal: null, 
npm WARN addRemoteGit cmd: 'git -c core.longpaths=true config --get remote.origin.url' } 
npm ERR! git clone --template=C:\Users\Dave the K\.atom\.apm\_git-remotes\_templates --mirror git@github.com:requirejs/text.git C:\Users\Dave the K\.atom\.apm\_git-remotes\git-github-com-requirejs-text-git-e7ab515b: Cloning into bare repository 'C:\Users\Dave the K\.atom\.apm\_git-remotes\git-github-com-requirejs-text-git-e7ab515b'... 
npm ERR! git clone --template=C:\Users\Dave the K\.atom\.apm\_git-remotes\_templates --mirror git@github.com:requirejs/text.git C:\Users\Dave the K\.atom\.apm\_git-remotes\git-github-com-requirejs-text-git-e7ab515b: Host key verification failed. 
npm ERR! git clone --template=C:\Users\Dave the K\.atom\.apm\_git-remotes\_templates --mirror git@github.com:requirejs/text.git C:\Users\Dave the K\.atom\.apm\_git-remotes\git-github-com-requirejs-text-git-e7ab515b: fatal: Could not read from remote repository. 
npm ERR! git clone --template=C:\Users\Dave the K\.atom\.apm\_git-remotes\_templates --mirror git@github.com:requirejs/text.git C:\Users\Dave the K\.atom\.apm\_git-remotes\git-github-com-requirejs-text-git-e7ab515b: 
npm ERR! git clone --template=C:\Users\Dave the K\.atom\.apm\_git-remotes\_templates --mirror git@github.com:requirejs/text.git C:\Users\Dave the K\.atom\.apm\_git-remotes\git-github-com-requirejs-text-git-e7ab515b: Please make sure you have the correct access rights 
npm ERR! git clone --template=C:\Users\Dave the K\.atom\.apm\_git-remotes\_templates --mirror git@github.com:requirejs/text.git C:\Users\Dave the K\.atom\.apm\_git-remotes\git-github-com-requirejs-text-git-e7ab515b: and the repository exists. 
npm ERR! Windows_NT 10.0.17134 
npm ERR! argv "C:\\Users\\Dave the K\\AppData\\Local\\atom\\app-1.28.1\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\Dave the K\\AppData\\Local\\atom\\app-1.28.1\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\Dave the K\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\Dave the K\\.atom\\.apmrc" "install" "C:\\Users\\DAVETH~1\\AppData\\Local\\Temp\\d-118611-19652-e217x0.i42fjn61or\\package.tgz" "--runtime=electron" "--target=2.0.4" "--arch=x64" "--global-style" 
npm ERR! node v6.9.5 
npm ERR! npm v3.10.10 
npm ERR! code 128 

npm ERR! Command failed: git -c core.longpaths=true clone --template=C:\Users\Dave the K\.atom\.apm\_git-remotes\_templates --mirror git@github.com:requirejs/text.git C:\Users\Dave the K\.atom\.apm\_git-remotes\git-github-com-requirejs-text-git-e7ab515b 
npm ERR! Cloning into bare repository 'C:\Users\Dave the K\.atom\.apm\_git-remotes\git-github-com-requirejs-text-git-e7ab515b'... 
npm ERR! Host key verification failed. 
npm ERR! fatal: Could not read from remote repository. 
npm ERR! 
npm ERR! Please make sure you have the correct access rights 
npm ERR! and the repository exists. 
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at: 
npm ERR! <https://github.com/npm/npm/issues> 

npm ERR! Please include the following file with any support request: 
npm ERR! C:\Users\DAVETH~1\AppData\Local\Temp\apm-install-dir-118611-19652-1l76r6v.pinx8khuxr\npm-debug.log 

C:\Users\Dave the K> 
===================================================== 

Thanks! 
Dave 
bilbo50 

----- Original Message -----

**Comment by bilbo50** [comment]
HI, 
It probably makes no difference, but just FYI, I decided to open another CMD.EXE window, as Admin this time, and ran the same apm command. Same results. 

Thanks, 
Dave 
bilbo 50 

----- Original Message -----

**Comment by bilbo50** [comment]
Hello,
is there another way to install the fountain-atom package without having to log into the repository remotely, simply to get fountain working in atom?

Thanks,
Dave
bilbo50

**Comment by superlou** [comment]
@bilbo50, this doesn't seem like a fountain-atom specific issue. Is it possible that it's an underlying problem related to [https://stackoverflow.com/questions/13363553/git-error-host-key-verification-failed-when-connecting-to-remote-repository](having an old SSH key)? Have you tried posting on the general [Atom forum](https://discuss.atom.io/). It's possible that this error message may have greater meaning to someone more familiar with Atom's package management in general.

**Comment by superlou** [comment]
@bilbo50, are you still experiencing this issue? I haven't been able to recreate this on my end.

**Comment by vekuda** [comment]
I am experiencing the same issue!

I have just installed Atom and some packages, but I can't install the fountain package. Exact same situation of @bilbo50
