### ISSUE TITLE
Contributing : first run error "Cannot find module 'underscore-plus'"

### ISSUE THREAD

**Issue by Tilix4** [superlou/fountain-atom#71]
Hi, I'm starting to contribute to this project.
I've forked your repository and cloned it in : `~/.atom/dev/packages`

Then I run `atom -d` and it displays this message : 

> Cannot find module 'underscore-plus'

Here is the stack trace : 

**Atom**: 1.28.2 x64
**Electron**: 2.0.5
**OS**: Mac OS X 10.11.6
**Thrown From**: [fountain](https://github.com/superlou/fountain-atom) package 0.7.3

### Stack Trace

Failed to activate the fountain package

```
At Cannot find module 'underscore-plus'

Error: Cannot find module 'underscore-plus'
    at Module._resolveFilename (module.js:543:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (/app.asar/src/module-cache.js:350:52)
    at Function.Module._load (module.js:473:25)
    at Module.require (module.js:586:17)
    at require (/app.asar/src/native-compile-cache.js:47:27)
    at /packages/fountain/lib/fountain-pdf-config-generator.coffee:3:5)
    at /packages/fountain/lib/fountain-pdf-config-generator.coffee:1:1)
    at /packages/fountain/lib/fountain-pdf-config-generator.coffee:1:1)
    at Module._compile (/app.asar/src/native-compile-cache.js:87:30)
    at /app.asar/src/compile-cache.js:235:23)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (module.js:586:17)
    at require (/app.asar/src/native-compile-cache.js:47:27)
    at /packages/fountain-atom/lib/fountain-pdf-converter.coffee:4:22)
    at /packages/fountain-atom/lib/fountain-pdf-converter.coffee:1:1)
    at /packages/fountain-atom/lib/fountain-pdf-converter.coffee:1:1)
    at Module._compile (/app.asar/src/native-compile-cache.js:87:30)
    at /app.asar/src/compile-cache.js:235:23)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (module.js:586:17)
    at require (/app.asar/src/native-compile-cache.js:47:27)
    at /packages/fountain-atom/lib/fountain.coffee:3:16)
    at /packages/fountain-atom/lib/fountain.coffee:1:1)
    at /packages/fountain-atom/lib/fountain.coffee:1:1)
    at Module._compile (/app.asar/src/native-compile-cache.js:87:30)
```

### Commands

```
     -6:55 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
```

### Non-Core Packages

```
date 2.1.0 
fountain 0.7.3 
fountain 0.7.3 
markdown-pdf 2.2.0 
pandoc 0.2.2 
pdf-view 0.70.0 
```

**Comment by jrbostic** [comment]
Run npm install

**Comment by Tilix4** [comment]
Ok thanks.
